### ISSUE TITLE
LED controll through custom commands

### ISSUE THREAD

**Issue by dismaster** [StefanCohen/OctoPrint-Dashboard#165]
When starting my printer - my LEDs are off in general.

In order to make this Dasboard better, i'd like to request a own button to turn these LEDs on/off.

Commands:
power on 100%: M150 R255 U255 B255
power off 0%: M150 R0 U0 B0

**Comment by StefanCohen** [comment]
Thanks for the feedback. My general stance is to not add controls to the dashboard (beyond start/stop/pause job). The reason is to reduce clutter and to stay focused on the goal: "A dashboard tab for Octoprint that displays the most relevant info regarding the state of the printer and any on-going print jobs". 

The purpose was never to replace the control tab where there already exists a feature to add buttons to execute gcode commands: https://docs.octoprint.org/en/master/features/custom_controls.html
