### ISSUE TITLE
Multiple instances of Dashboard

### ISSUE THREAD

**Issue by tedukes** [StefanCohen/OctoPrint-Dashboard#169]
Hello,
Really enjoy using your dashboard plugin.
I have recently added another printer and have multiple instances of Octoprint running with multiple webcams.
It would be awesome if I could have Dashboard running on both instances.
Thank you!

**Comment by StefanCohen** [comment]
Are you running two instances of Octoprint on the same host? That’s not something I’ve tried so I dont’t know what would happen. What problems are you running into?

**Comment by tedukes** [comment]
Hi,

 

Right, I’m running 2 instances on a single RPi. I followed Chris Riley’s video on Youtube to get it working. https://www.youtube.com/watch?v=7Saa1HpLRoM

 

The only issue is its only running on the first instance. No dashboard on the second. I’m not sure why its not available as other plugins are.

 

Thanks!

**Comment by StefanCohen** [comment]
Can you please attach the octoprint log for the second instance?

**Comment by jneilliii** [comment]
I've had to deal with this issue before @StefanCohen. Any places where you are making API calls or loading URLs from your plugin side, you need to make the URL relatives to the global variables API_BASEURL or BASEURL.

**Comment by tedukes** [comment]
Hello,

 

I don’t believe there is a log for the second instance, unless its somewhere I’m not aware of. I have attached /var/log/message and /var/log/webcam2

 

Thanks!

**Comment by KenLucke** [comment]
> Are you running two instances of Octoprint on the same host? That’s not something I’ve tried so I dont’t know what would happen. What problems are you running into?

Used to work (v1.11.4)  Now, it only shows the webcam on one of the instances...  If I reload one, it starts showing the webcam on the other, and loses it on the one reloaded.

https://www.dropbox.com/s/lbfrwkv2womwchj/screencast%202020-05-30%2020-15-49.mp4

Started about the time you and the author of FloatingNavBar started tinkering due to my request over there.  Disabling/Removing FloatingNavBar does not change the behavior.

**Comment by KenLucke** [comment]
> Getting two webcams working was tough. Watched Chris Riley’s video numerous time. I pretty much gave up. Could see both cams on the first instance but nothing but a snapshot on the second. One day, it just started working by itself. Crazy!

Not using two webcams.  Same webcam, two instances of the same OcctoPrint.

**Comment by StefanCohen** [comment]
I have to say that I'm quite confused. I still don't understand what the problem is. @KenLucke Please create a new issue as your problem doesn't seem to be related to running multiple octoprint instances.

@tedukes I don't have much to go on here. Can you please try to describe the problem in detail? Is the Dasboard tab completely missing in the second instance? I will also need an octoprint log file for each of the instances to begin digging.

**Comment by StefanCohen** [comment]
Thanks for the update. Please attach the logs on the Github page. It seems like they are lost when replying via email.

**Comment by tedukes** [comment]
here ya go
![Ender3](https://user-images.githubusercontent.com/48227936/83535240-c6d86280-a4bf-11ea-87e8-87e3cb235db0.jpg)
[octoprint_logs.zip](https://github.com/StefanCohen/OctoPrint-Dashboard/files/4717923/octoprint_logs.zip)
![PrusaBear](https://user-images.githubusercontent.com/48227936/83535244-c8098f80-a4bf-11ea-8602-b00fe352b010.jpg)

**Comment by jneilliii** [comment]
Still no logs @tedukes?

**Comment by tedukes** [comment]
Posted on Github. look between the 2 pics.


-------- Original Message --------
Subject: Re: [StefanCohen/OctoPrint-Dashboard] Multiple instances of
Dashboard (#169)

**Comment by StefanCohen** [comment]
It seems like both Dashboard and DLP are disabled in the second instance. Can you try to enable them in the plugin manager?

**Comment by tedukes** [comment]
Thanks!! That was the problem. Didn't occur to me it needed to be enabled.

**Comment by StefanCohen** [comment]
No problem. Closing this issue then.
