### ISSUE TITLE
User Adjustable Order of GUI

### ISSUE THREAD

**Issue by Connor2811** [StefanCohen/OctoPrint-Dashboard#179]
**Is your feature request related to a problem? Please describe.**
I would love to have the most important data at the top of the dashboard so I don't have to search. 

**Describe the solution you'd like**
a way for a user to move around the widgets to be in any order or position they'd like

**Describe alternatives you've considered**
none that work as well as your incredible plugin

**Additional context**
none

**Comment by StefanCohen** [comment]
Thanks for the feedback. I have actually evaluated ways to make the UI fully adjustable in this thread: https://community.octoprint.org/t/dashboard-v2-ideas/12717/18

I have created two semi-working prototypes so far but I'm not satisfied with any of them.

I feel that this would require a full re-write of most of the Dashboard and I'm not willing to put in the  amount of hours needed at this point. That's why I will reject this feature request.

Regards,
Stefan
