### ISSUE TITLE
Configurable Temperature Maximums

### ISSUE THREAD

**Issue by doughoyt** [StefanCohen/OctoPrint-Dashboard#3]
First, a quick thank you on an excellent plugin--I think this will be much easier to gauge the overall status and more informative than staring at the temperature graphs and looking for progress in the fine print.

It appears, however, that all the dashboardGuages have a hard-coded max of 300.  This might be appropriate for hotends, but bed (and chamber) temps would never come close.  I am barely using 25% of the graph.

It would be nice to have the max temps on those gauges configurable, so we can set the different types individually.

I've made the change manually on my machine to my desired max for the bed temp (100), but will likely lose the changes with any upgrade.

I would be happy to try to tackle this enhancement, if it would be beneficial to the project.

**Comment by StefanCohen** [comment]
I agree and it has been on my own todo-list since I added the gauges. I'm thinking that it would be enough to specify the max temp per category (hotend, bed, chamber) instead of on individual tools, etc... I also think the max temp should be displayed on each gauge. Feel free to contribute a PR if you want to.
