### ISSUE TITLE
Missing DHT11 sensor data

### ISSUE THREAD

**Issue by joeynuggetz** [StefanCohen/OctoPrint-Dashboard#90]
Did the latest version break humidity/sensor? Was working fine a few days ago. Not getting any readings now. Would be nice if each had their own icon too and maybe some docs on whether to use the physical GPIO pin or GPI number. I just guessed and got it to work.

**Comment by StefanCohen** [comment]
I've had no other reports of that and my DHT11 works fine on two separate systems with 1.10.2.
I'm regardless working on removing the current implementation of sensor support. It will be replaced with a binding to the Enclosure plugin since it supports a better variety of sensors. I plan to push that within the next couple of days.

**Comment by StefanCohen** [comment]
WIP:

![Screenshot 2019-10-11 at 00 29 28](https://user-images.githubusercontent.com/33824565/66611286-4d9d9f80-ebbe-11e9-9a9c-f4b0113253ee.png)
